### ISSUE TITLE
After update: HAP-BLE failed with request 5

### ISSUE THREAD

**Issue by SFKV** [grover/homebridge-ranger#28]
I've just updated my eve energy to the software revision 1.2.9. Not a smart move, since everything was working (somewhat, I had to monitor homebridge for stalls and fails and restart the service or reboot depending on the circumstances - but thats readily automated).

Now I get these friggin BLE failures:

```Aug 07 21:05:52 pizeroW homebridge[227]: [2019-8-7 21:05:52] [Ranger] Connecting to Eve Energy B253
Aug 07 21:05:53 pizeroW homebridge[227]: [2019-8-7 21:05:53] [Ranger] Discovered services.
Aug 07 21:05:53 pizeroW homebridge[227]: [2019-8-7 21:05:53] [Ranger] Discovered GATT services and characteristics of Eve Energy B253
Aug 07 21:05:53 pizeroW homebridge[227]: [2019-8-7 21:05:53] [Ranger] Connected to Eve Energy B253
Aug 07 21:05:53 pizeroW homebridge[227]: [2019-8-7 21:05:53] [Ranger] Connected to Eve Energy B253
Aug 07 21:05:53 pizeroW homebridge[227]: 2019-08-07T19:05:53.793Z ranger:Eve Energy B253:events Enable all subscriptions on the device.
Aug 07 21:05:53 pizeroW homebridge[227]: 2019-08-07T19:05:53.863Z ranger:Eve Energy B253:errors Failed to read e863f007079e48ff8f279c2605a29f52:000000230000100080000026bb765291 - Error: HAP-BLE request failed with status 5 at HapExecutor
Aug 07 21:05:53 pizeroW homebridge[227]: 2019-08-07T19:05:53.867Z ranger:Eve Energy B253:errors Failed to refresh characteristic e863f007079e48ff8f279c2605a29f52:000000230000100080000026bb765291
Aug 07 21:05:53 pizeroW homebridge[227]: 2019-08-07T19:05:53.938Z ranger:Eve Energy B253:errors Failed to read e863f007079e48ff8f279c2605a29f52:e863f112079e48ff8f279c2605a29f52 - Error: HAP-BLE request failed with status 5 at HapExecutor
Aug 07 21:05:53 pizeroW homebridge[227]: 2019-08-07T19:05:53.942Z ranger:Eve Energy B253:errors Failed to refresh characteristic e863f007079e48ff8f279c2605a29f52:e863f112079e48ff8f279c2605a29f52
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.028Z ranger:Eve Energy B253:errors Failed to read 000000470000100080000026bb765291:000000230000100080000026bb765291 - Error: HAP-BLE request failed with status 5 at HapExecutor
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.032Z ranger:Eve Energy B253:errors Failed to refresh characteristic 000000470000100080000026bb765291:000000230000100080000026bb765291
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.088Z ranger:Eve Energy B253:errors Failed to read 000000470000100080000026bb765291:000000250000100080000026bb765291 - Error: HAP-BLE request failed with status 5 at HapExecutor
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.092Z ranger:Eve Energy B253:errors Failed to refresh characteristic 000000470000100080000026bb765291:000000250000100080000026bb765291
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.164Z ranger:Eve Energy B253:errors Failed to read 000000470000100080000026bb765291:000000260000100080000026bb765291 - Error: HAP-BLE request failed with status 5 at HapExecutor
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.170Z ranger:Eve Energy B253:errors Failed to refresh characteristic 000000470000100080000026bb765291:000000260000100080000026bb765291
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.224Z ranger:Eve Energy B253:errors Failed to read 000000470000100080000026bb765291:e863f10a079e48ff8f279c2605a29f52 - Error: HAP-BLE request failed with status 5 at HapExecutor
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.230Z ranger:Eve Energy B253:errors Failed to refresh characteristic 000000470000100080000026bb765291:e863f10a079e48ff8f279c2605a29f52
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.284Z ranger:Eve Energy B253:errors Failed to read 000000470000100080000026bb765291:e863f126079e48ff8f279c2605a29f52 - Error: HAP-BLE request failed with status 5 at HapExecutor
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.290Z ranger:Eve Energy B253:errors Failed to refresh characteristic 000000470000100080000026bb765291:e863f126079e48ff8f279c2605a29f52
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.389Z ranger:Eve Energy B253:errors Failed to read 000000470000100080000026bb765291:e863f10d079e48ff8f279c2605a29f52 - Error: HAP-BLE request failed with status 5 at HapExecutor
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.395Z ranger:Eve Energy B253:errors Failed to refresh characteristic 000000470000100080000026bb765291:e863f10d079e48ff8f279c2605a29f52
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.464Z ranger:Eve Energy B253:errors Failed to read 000000470000100080000026bb765291:e863f10c079e48ff8f279c2605a29f52 - Error: HAP-BLE request failed with status 5 at HapExecutor
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.470Z ranger:Eve Energy B253:errors Failed to refresh characteristic 000000470000100080000026bb765291:e863f10c079e48ff8f279c2605a29f52
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.541Z ranger:Eve Energy B253:errors Failed to read 000000470000100080000026bb765291:000000a70000100080000026bb765291 - Error: HAP-BLE request failed with status 5 at HapExecutor
Aug 07 21:05:54 pizeroW homebridge[227]: 2019-08-07T19:05:54.547Z ranger:Eve Energy B253:errors Failed to refresh characteristic 000000470000100080000026bb765291:000000a70000100080000026bb765291
Aug 07 21:06:02 pizeroW homebridge[227]: [2019-8-7 21:06:02] [Ranger] Device Eve Degree 4191 issued a disconnected event.
Aug 07 21:06:03 pizeroW homebridge[227]: 2019-08-07T19:06:03.680Z ranger:Eve Energy B253:reads Reading e863f007079e48ff8f279c2605a29f52:e863f116079e48ff8f279c2605a29f52
Aug 07 21:06:03 pizeroW homebridge[227]: 2019-08-07T19:06:03.767Z ranger:Eve Energy B253:errors Failed to read e863f007079e48ff8f279c2605a29f52:e863f116079e48ff8f279c2605a29f52 - Error: HAP-BLE request failed with status 5 at HapExecutor
Aug 07 21:06:22 pizeroW homebridge[227]: [2019-8-7 21:06:22] [Ranger] Reported reachability for Eve Energy B253: false
Aug 07 21:06:33 pizeroW homebridge[227]: [2019-8-7 21:06:33] [Ranger] Disconnected from Eve Energy B253
```

**Comment by hansvangent** [comment]
I've should have checked this before updating this afternoon, homebridge doesn't even seem to start at my install anymore. Not seeing this error though, but I probably have the same issue :-/

@SFKV did you find a solution?

**Comment by hansvangent** [comment]
Anything? @grover do you potentially have an idea what this could be?

**Comment by SFKV** [comment]
Hope this comes through to you. You need to change the addresses of your devices, they change with every update and anytime you unpair one..

Sent from my mobile device

**Comment by hansvangent** [comment]
@SFKV ah crap so I have to unpair it, reset it on the device and then do another pair? Will try that over the weekend when I'm on-site again hopefully that works.

**Comment by hansvangent** [comment]
Per [these instructions](https://github.com/grover/homebridge-ranger/blob/master/docs/pairing/remove-pairing.md)  I've added the "remove: true" to the config.

But in the log it states:
`Aug 22 16:26:49 unifipi homebridge[15726]: [2019-8-22 16:26:49] [Ranger] Found paired accessory Eve address=XX:XX:XX:XX:XX:XX rssi=-72dB

Aug 22 16:26:52 unifipi homebridge[15726]: [2019-8-22 16:26:52] [Ranger] Found paired accessory Eve address=XX:XX:XX:XX:XX:XX rssi=-90dB

Aug 22 16:26:53 unifipi homebridge[15726]: [2019-8-22 16:26:53] [Config] Console v4.6.0 is listening on :: port 1234

Aug 22 16:28:10 unifipi homebridge[15726]: [2019-8-22 16:28:10] [Config] [HapClient] Cannot load accessories. No Homebridge instances have been discovered.

Aug 22 16:28:10 unifipi homebridge[15726]: [2019-8-22 16:28:10] [Config] [HapClient] Cannot load accessories. No Homebridge instances have been discovered.`

**Comment by hansvangent** [comment]
Oh wait nevermind, I could just update the address indeed in my config :-/

And now I see the following error:

> Aug 22 16:46:19 unifipi homebridge[16829]: [2019-8-22 16:46:19] [Ranger] Accessory 'Eve Energy' found.
Aug 22 16:46:19 unifipi homebridge[16829]: (node:16829) UnhandledPromiseRejectionWarning: Error: Command Disallowed (0xc)
Aug 22 16:46:19 unifipi homebridge[16829]:     at NobleBindings.onLeConnComplete (/opt/node-v9.3.0-linux-armv7l/lib/node_modules/homebridge-ranger/node_modules/noble/lib/hci-socket/bindings.js:220:13)
Aug 22 16:46:19 unifipi homebridge[16829]:     at Hci.emit (events.js:159:13)
Aug 22 16:46:19 unifipi homebridge[16829]:     at Hci.processCmdStatusEvent (/opt/node-v9.3.0-linux-armv7l/lib/node_modules/homebridge-ranger/node_modules/noble/lib/hci-socket/hci.js:674:12)
Aug 22 16:46:19 unifipi homebridge[16829]:     at Hci.onSocketData (/opt/node-v9.3.0-linux-armv7l/lib/node_modules/homebridge-ranger/node_modules/noble/lib/hci-socket/hci.js:469:12)
Aug 22 16:46:19 unifipi homebridge[16829]:     at BluetoothHciSocket.emit (events.js:159:13)
Aug 22 16:46:19 unifipi homebridge[16829]: (node:16829) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Aug 22 16:46:19 unifipi homebridge[16829]: (node:16829) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

which is a different error then yours, but it is an error nontheless and not working at the moment

@SFKV @grover

**Comment by grover** [comment]
As you guys discovered the accessories do change their bluetooth mac address during the upgrade. This is one of the reasons, why advise not to upgrade per the docs.

To solve your problem: Reset the Eve Energy by pressing the little push button light until it blinks and then pair it as if it were a new device. you’ll have to reconfigure your rules in HomeKit.

**Comment by hansvangent** [comment]
Check that resolved it for me, thanks! :-)

**Comment by SFKV** [comment]
I concur. This solved the problem. Simply updating the addresses does not work. Thanks @grover !
