### ISSUE TITLE
Onvis Motion Sensor Pairing

### ISSUE THREAD

**Issue by bryangauvin** [grover/homebridge-ranger#29]
Been at this for days now. Followed all instructions. If I dont list the accessory in the config homebrige comes up it shows it found the unpaired item but never auto pairs it.

When I put the device into config I get the following and homebridge crashes.

Config:
{
    "bridge": {
        "name": "Extender",
        "username": "CC:26:3D:E5:CE:30",
        "port": 8085,
        "pin": "031-45-160"
    },
    "platforms": [
        {
            "platform": "Ranger",
            "devices": [
                {
                    "name": "Onvis-SMS1-3cf5c4",
                    "address": "c7:be:d1:ab:c5:57",
                    "pin": "943-66-752"
                }
            ]
        },
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "sudo": true,
            "restart": "sudo -n systemctl restart homebridge",
            "log": {
                "method": "systemd",
                "service": "homebridge"
            }
        }
    ],
    "accessories": []
}

Log:
[2019-9-2 15:23:12] Loaded config.json with 0 accessories and 2 platforms.
[2019-9-2 15:23:12] ---
[2019-9-2 15:23:13] Loaded plugin: homebridge-config-ui-x
[2019-9-2 15:23:13] Registering platform 'homebridge-config-ui-x.config'
[2019-9-2 15:23:13] ---
[2019-9-2 15:23:15] Loaded plugin: homebridge-ranger
[2019-9-2 15:23:15] Registering platform 'homebridge-ranger.Ranger'
[2019-9-2 15:23:15] ---
[2019-9-2 15:23:16] Loading 2 platforms...
[2019-9-2 15:23:16] [Ranger] Initializing Ranger platform...
[2019-9-2 15:23:16] [Ranger] Ranger Platform Plugin Loaded
[2019-9-2 15:23:16] [Ranger] Found device in config: "Onvis-SMS1-3cf5c4"
[2019-9-2 15:23:16] [Ranger] Waiting for accessory: Onvis-SMS1-3cf5c4
[2019-9-2 15:23:16] [Ranger] Not all accessories have their devices. Not publishing yet.
[2019-9-2 15:23:16] [Config] Initializing config platform...
[2019-9-2 15:23:16] [Config] Spawning homebridge-config-ui-x with PID 5940
[2019-9-2 15:23:16] Loading 0 accessories...
[2019-9-2 15:23:16] [Ranger] DidFinishLaunching
[2019-9-2 15:23:17] [Ranger] Found paired accessory Yale Lock address=e8:cf:08:0b:94:3c rssi=-87dB
[2019-9-2 15:23:20] [Ranger] Found unpaired accessory Onv address=c7:be:d1:ab:c5:57 rssi=-64dB
[2019-9-2 15:23:20] [Ranger] Accessory 'Onvis-SMS1-3cf5c4' found.
[2019-9-2 15:23:28] [Ranger] Discovered services.
[2019-9-2 15:23:28] [Ranger] Discovered GATT services and characteristics of Onvis-SMS1-3cf5c4
[2019-9-2 15:23:28] [Ranger] Connected to Onvis-SMS1-3cf5c4
[2019-9-2 15:23:33] [Ranger] Disconnected from Onvis-SMS1-3cf5c4
(node:5916) UnhandledPromiseRejectionWarning: Error: Disconnected
    at HapBleDevice._rejectPendingOperations (/opt/node-v9.3.0-linux-armv6l/lib/node_modules/homebridge-ranger/src/hap/HapBleDevice.js:248:17)
    at HapBleDevice._onDisconnected (/opt/node-v9.3.0-linux-armv6l/lib/node_modules/homebridge-ranger/src/hap/HapBleDevice.js:131:12)
    at Peripheral.emit (events.js:159:13)
    at Noble.onDisconnect (/opt/node-v9.3.0-linux-armv6l/lib/node_modules/homebridge-ranger/node_modules/noble/lib/noble.js:206:16)
    at NobleBindings.emit (events.js:159:13)
    at NobleBindings.onDisconnComplete (/opt/node-v9.3.0-linux-armv6l/lib/node_modules/homebridge-ranger/node_modules/noble/lib/hci-socket/bindings.js:259:10)
    at Hci.emit (events.js:159:13)
    at Hci.onSocketData (/opt/node-v9.3.0-linux-armv6l/lib/node_modules/homebridge-ranger/node_modules/noble/lib/hci-socket/hci.js:443:12)
    at BluetoothHciSocket.emit (events.js:159:13)
(node:5916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-9-2 15:23:33] [Ranger] Device Onvis-SMS1-3cf5c4 issued a disconnected event.
[2019-9-2 15:23:33] [Ranger] Reported reachability for Onvis-SMS1-3cf5c4: true
[2019-9-2 15:23:42] [Config] Homebridge Config UI X v4.6.1 is listening on :: port 8080
homebridge : TTY=pts/0 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
pam_unix(sudo:session): session opened for user root by (uid=0)
homebridge : TTY=pts/2 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
pam_unix(sudo:session): session opened for user root by (uid=0)
homebridge : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/kill -9 5993
pam_unix(sudo:session): session opened for user root by (uid=0)
pam_unix(sudo:session): session closed for user root
[2019-9-2 15:24:26] [Config] Multiple Instances Of Homebridge Found Installed
[2019-9-2 15:24:26] [Config] /opt/node-v9.3.0-linux-armv6l/lib/node_modules/homebridge
[2019-9-2 15:24:26] [Config] /usr/local/lib/node_modules/homebridge
homebridge : TTY=pts/2 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
pam_unix(sudo:session): session opened for user root by (uid=0)
homebridge : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/kill -9 6011
pam_unix(sudo:session): session opened for user root by (uid=0)
[2019-9-2 15:26:01] [Config] Multiple Instances Of Homebridge Found Installed
pam_unix(sudo:session): session closed for user root
[2019-9-2 15:26:01] [Config] /opt/node-v9.3.0-linux-armv6l/lib/node_modules/homebridge
[2019-9-2 15:26:01] [Config] /usr/local/lib/node_modules/homebridge
homebridge : TTY=pts/2 ; PWD=/var/lib/homebridge ; USER=root ; COMMAND=/bin/journalctl -o cat -n 500 -f -u homebridge
pam_unix(sudo:session): session opened for user root by (uid=0)

**Comment by bryangauvin** [comment]
@grover do you have any idea what I’m doing wrong here. I’ve been stuck for weeks now 
@grover

**Comment by poldueta** [comment]
Hi @bryangauvin ! Do you have any progress on that problem?
