### ISSUE TITLE
Problem bluetooth-hci-socket on raspberry

### ISSUE THREAD

**Issue by sorriso93** [grover/homebridge-ranger#34]
I tried node 9, 10 and 11 on fresh raspberry installation. No way to get it run, it seems that a subcomponent of noble doesn't install, bluetooth-hci-socket.

/root/.node-gyp/11.15.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/root/.node-gyp/11.15.0/include/node/v8.h:9710:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [binding.target.mk:99: Release/obj.target/binding/src/BluetoothHciSocket.o] Error 1
make: uscita dalla directory "/usr/local/lib/node_modules/homebridge-ranger/node_modules/bluetooth-hci-socket/build"
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.19.75+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-ranger/node_modules/bluetooth-hci-socket
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/homebridge-ranger/node_modules/bluetooth-hci-socket):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ homebridge-ranger@0.3.4
updated 1 package in 679.517s

Any suggestion? 
many thanks

**Comment by sorriso93** [comment]
I also tried installing manually noble abandonware, same result

**Comment by curana** [comment]
I got it to work with abandonware's bluetooth-hci-socket.

It works for a few minutes, then the connection to my Eve Energy is lost and I have to restart Homebridge.

**Comment by sorriso93** [comment]
> I got it to work with abandonware's bluetooth-hci-socket.
> 
> It works for a few minutes, then the connection to my Eve Energy is lost and I have to restart Homebridge.

can you share the steps you made to install it? on a raspberry with raspbian? thanks

**Comment by curana** [comment]
Try installing from this repo with node v12:
https://github.com/palasinio/homebridge-ranger

**Comment by sorriso93** [comment]
Installed, configured and extended my koogeek contact sensor. But the state doesn't get updated when I open the window or close...

**Comment by gewaechshaus** [comment]
@sorriso93 - same here, no status Updates from a Eve door sensor...

**Comment by palasinio** [comment]
Have you played with reachabilityTimeout? For example 120000?
