### ISSUE TITLE
cant pair eve door

### ISSUE THREAD

**Issue by jsc1970** [grover/homebridge-ranger#7]
Hello Grover,
for a test i have paired one eve room it works, after then i have tried to pair a eve door.
With eve door it comes an error.

here is my log with eve door:

[2018-7-17 19:17:53] Loading 1 platforms...
[2018-7-17 19:17:53] [Ranger] Initializing Ranger platform...
[2018-7-17 19:17:53] [Ranger] Ranger Platform Plugin Loaded
[2018-7-17 19:17:53] [Ranger] Found device in config: "Tor"
[2018-7-17 19:17:53] [Ranger] Found device in config: "Flur unten"
[2018-7-17 19:17:53] [Ranger] Waiting for accessory: Tor
[2018-7-17 19:17:53] [Ranger] Not all accessories have their devices. Not publishing yet.
[2018-7-17 19:17:53] Loading 0 accessories...
[2018-7-17 19:17:53] [Ranger] DidFinishLaunching
[2018-7-17 19:17:53] [Ranger] Starting to scan for BLE HomeKit accessories
[2018-7-17 19:17:53] [Ranger] Found paired accessory Eve Energy 6C21 address=de:30:78:27:96:a1 rssi=-89dB
[2018-7-17 19:17:53] [Ranger] Found unpaired accessory Eve Door 1F1B address=e9:c8:14:83:c2:98 rssi=-88dB
[2018-7-17 19:17:53] [Ranger] Accessory 'Tor' found.
[2018-7-17 19:17:53] [Ranger] Waiting for accessory: Flur unten
[2018-7-17 19:17:53] [Ranger] Not all accessories have their devices. Not publishing yet.
[2018-7-17 19:17:53] [Ranger] Found paired accessory FIBARO Single Switch  address=ac:17:02:2e:8d:2c rssi=-61dB
[2018-7-17 19:17:53] [Ranger] Found paired accessory Eve address=c7:89:58:78:a3:54 rssi=-98dB
[2018-7-17 19:17:54] [Ranger] Found paired accessory Eve Room 024F address=e8:e7:04:f9:ce:7c rssi=-80dB
[2018-7-17 19:17:54] [Ranger] Accessory 'Flur unten' found.
[2018-7-17 19:17:55] [Ranger] Scanning stopped externally. Restarting in 2s.
[2018-7-17 19:17:55] [Ranger] Discovered services.
[2018-7-17 19:17:56] [Ranger] Discovered GATT services and characteristics of Tor
[2018-7-17 19:17:56] [Ranger] Connected to Tor
(node:984) UnhandledPromiseRejectionWarning: Error: HAP-BLE request failed with status 4
    at HapExecutor._getResponsePayload (/homebridge/node_modules/homebridge-ranger/src/hap/HapExecutor.js:135:13)
    at HapExecutor._executeCommand (/homebridge/node_modules/homebridge-ranger/src/hap/HapExecutor.js:64:34)
    at <anonymous>
(node:984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-7-17 19:18:07] [Ranger] Reported reachability for Flur unten: true
[2018-7-17 19:18:31] [Ranger] Tor: First advertisement after 38475ms.
[2018-7-17 19:18:31] [Ranger] Disconnected from Tor
[2018-7-17 19:18:38] [Ranger] Reported reachability for Tor: true

and here the log without door, system works:

[2018-7-17 19:21:11] [Ranger] DidFinishLaunching
[2018-7-17 19:21:11] [Ranger] Starting to scan for BLE HomeKit accessories
[2018-7-17 19:21:11] [Ranger] Found paired accessory FIBARO Single Switch  address=ac:17:02:2e:8d:2c rssi=-70dB
[2018-7-17 19:21:11] [Ranger] Found paired accessory Eve Energy AD81 address=c7:89:58:78:a3:54 rssi=-92dB
[2018-7-17 19:21:11] [Ranger] Found paired accessory Eve Energy 6C21 address=de:30:78:27:96:a1 rssi=-89dB
[2018-7-17 19:21:11] [Ranger] Found paired accessory Eve Room 024F address=e8:e7:04:f9:ce:7c rssi=-78dB
[2018-7-17 19:21:11] [Ranger] Accessory 'Flur unten' found.
[2018-7-17 19:21:11] [Ranger] Connecting to Flur unten
[2018-7-17 19:21:12] [Ranger] Found unpaired accessory Eve Door 1F1B address=e9:c8:14:83:c2:98 rssi=-89dB
[2018-7-17 19:21:13] [Ranger] Scanning stopped externally. Restarting in 2s.
[2018-7-17 19:21:13] [Ranger] Discovered services.
[2018-7-17 19:21:15] [Ranger] Discovered GATT services and characteristics of Flur unten
[2018-7-17 19:21:15] [Ranger] Connected to Flur unten
[2018-7-17 19:21:15] [Ranger] Connected to Flur unten
[2018-7-17 19:21:15] [Ranger] Securing connection to Flur unten
[2018-7-17 19:21:15] [Ranger] Returning pair verify request for M1
[2018-7-17 19:21:16] [Ranger] Received pair verify response for M2
[2018-7-17 19:21:16] [Ranger] Returning pair verify request for M3
[2018-7-17 19:21:17] [Ranger] Received pair verify response for M4
[2018-7-17 19:21:17] [Ranger] Secure connection to Flur unten established.
[2018-7-17 19:21:17] [Ranger] Retrieved accessory information Manufacturer=Elgato Systems
[2018-7-17 19:21:17] [Ranger] Retrieved accessory information Model=Eve Room
[2018-7-17 19:21:18] [Ranger] Retrieved accessory information Name=Eve Room
[2018-7-17 19:21:18] [Ranger] Retrieved accessory information Serial Number=BU44E1A13637
[2018-7-17 19:21:18] [Ranger] Retrieved accessory information Firmware Revision=1.3.1;466
[2018-7-17 19:21:18] [Ranger] Publishing BLE service 0000008A-0000-1000-8000-0026BB765291 via proxy
[2018-7-17 19:21:18] [Ranger] Publishing BLE service 00000082-0000-1000-8000-0026BB765291 via proxy
[2018-7-17 19:21:18] [Ranger] Publishing BLE service 0000008D-0000-1000-8000-0026BB765291 via proxy
[2018-7-17 19:21:18] [Ranger] Publishing BLE service 00000096-0000-1000-8000-0026BB765291 via proxy
[2018-7-17 19:21:18] [Ranger] Publishing BLE service E863F007-079E-48FF-8F27-9C2605A29F52 via proxy
[2018-7-17 19:21:18] [Ranger] Initializing platform accessory 'Flur unten'...
Setup Payload:
X-HM://0023ISYWYNM3L
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:

**Comment by johndf** [comment]
Hi,
Did you get an answer to this?
I'm getting the following error trying to connect to an Elgato Eve Aqua (called bamboopi)

[2018-11-9 23:07:28] [Ranger] Connected to Bamboopi
(node:16259) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: HAP-BLE request failed with status 4
(node:16259) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-11-9 23:08:04] [Ranger] Disconnected from Bamboopi

Thanks
Johndf

**Comment by jsc1970** [comment]
Hi,

No Answer.

Joerg

**Comment by grover** [comment]
Version 0.3.3 should fix this.
